### ISSUE TITLE
Improving handling of parse errors in test files (running with Node)

### ISSUE THREAD

**Issue by mik01aj** [jasmine/jasmine#1017]
I use jasmine with Node like this:

```
jasmine.loadConfig({
    'spec_dir': 'app',
    'spec_files': [
        '**/**/test.{js,jsx}',
    ],
});
```

Then, if any of the test files has invalid syntax (possibly because of invalid babel config or anything), I get this stacktrace:

```
/Users/mikolajdadela/code/lb-react-frontend/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:987
      currentRunnable().addExpectationResult(false, {
                       ^

TypeError: Cannot read property 'addExpectationResult' of undefined
    at Env.fail (/Users/mikolajdadela/code/lb-react-frontend/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:987:24)
    at jasmineInterface.fail (/Users/mikolajdadela/code/lb-react-frontend/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3423:23)
    at process.<anonymous> (/Users/mikolajdadela/code/lb-react-frontend/jasmineTestSuite.js:20:5)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:221:26)
```

Note that it this big error report never actually mentions the file that caused the parse error.

I'm currently using jasmine `2.4.1`.

**Comment by slackersoft** [comment]
It looks like that error is coming from within the `fail` function, which is only intended for use while the suite is running. Do you have code that calls it when a parse error occurs? That could be causing this behavior.

Given the reason the error is occurring within Jasmine itself, the only thing we might want to change would be to make the message for the error indicate that `fail` was called in an invalid context, but that wouldn't really solve your problem directly.

We'd be happy to review a pull request to make `fail` throw a more distinctive error in this case, similar to that thrown for `expect`.

Thanks for using Jasmine!

**Comment by mik01aj** [comment]
A ha! So now I know where it's coming from! That's what I do a few lines before:

```
process.on('uncaughtException', function(err) {
    // NOTE: We're not using console.error, as it might have been mocked
    fail('Uncaught exception in async code: ' + err + '\n' + err.stack);
});
```

**Comment by csymeonides** [comment]
Just to add to @dcbrwn's comment: if you want to set the window size upfront like I did, instead of a beforeAll you can use chromeOptions in your config.js [as suggested here](http://stackoverflow.com/a/40284389/3794038)

**Comment by slackersoft** [comment]
@dcbrwn, your issue should be fixed on master and in 2.5.1, now that Jasmine allows the global suite to have expectations. See #811.

**Comment by csymeonides** [comment]
@slackersoft I'm not sure that's true. I'm using 2.5.2 and still getting the same error, so I had to get rid of my beforeAll.

**Comment by slackersoft** [comment]
Hmm, I just tried this suite:

```javascript
beforeAll(function(done) {
  setTimeout(done.fail, 1000);
});

it('should be a thing', function() {
  expect(true).toEqual(true);
});
```

And I'm seeing it report a global error in both 2.5.2 and edge, but fail with a timeout in 2.4.
