### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'allKeys[i].match(/^[0-9]+$/)')

### ISSUE THREAD

**Issue by mbuckley** [jasmine/jasmine#1195]
**Version:** 2.5.0

**Exception**
TypeError: undefined is not a constructor (evaluating 'allKeys[i].match(/^[0-9]+$/)') in ~/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 2989)

**Assertion triggering exeption**
expect(window.alert).toHaveBeenCalledWith 'response'

**Overview**
After updating jasmine-core from v2.4.1 to v2.5.0 I am seeing the following exception. With the changes to the eq function for v2.5.0, it seems to be caused by the following loop block.

jasmine-core/lib/jasmine.js ~ line 2988
```
for (var i in allKeys) {
  if (!allKeys[i].match(/^[0-9]+$/)) { // line 2988
    extraKeys.push(allKeys[i]);
   }
}
```

If I add a guard check for hasOwnProperty it resolves the issue. I'm not familiar enough with this code to know if this is the correct solution. Should this loop also be checking inherit properties or should it exclude them?

// hasOwnProperty example code that resolves the exception
```
for (var i in allKeys) {
  if (allKeys.hasOwnProperty(i)) { // guard that resolves issue
    if (!allKeys[i].match(/^[0-9]+$/)) {
      extraKeys.push(allKeys[i]);
    }
  }
}
```

Has anyone else run into this?

**Comment by olgabuksa** [comment]
We are facing the same problem in our big project. Please fix it ASAP

**Comment by mbuckley** [comment]
@olgabuksa We've worked around the issue by locking to version 2.4.1 for now.

**Comment by Sygnious** [comment]
I got the same error as well, before going back to 2.4.1.

Before the reversion, I found out that this error happens when you compare two arrays with toEqual (expect(...).toEqual(...)), and both are **equal**.

If unequal, you get the standard error message showing the contents. If they are equal, you get TypeError: undefined is not a constructor.

It sounds more like an error in jasmine-core, if you ask me.

**Comment by seanparmelee** [comment]
I believe this was fixed with https://github.com/jasmine/jasmine/pull/1192 (for https://github.com/jasmine/jasmine/issues/1188).

**Comment by olgabuksa** [comment]
It's not fixed yet. @mbuckley, how to lock 2.4.1?  npm install is downloading latest version jasmine-core...

**Comment by mbuckley** [comment]
@olgabuksa If you are using npm, you can lock the version by using either a tilde which will allow patch updates, or just specify the version with no prefix.

// patch updates
```
"devDependencies": {
  "jasmine-core": "~2.4.1"
}
```

// lock version at 2.4.1
```
"devDependencies": {
  "jasmine-core": "2.4.1"
}
```

**Comment by Rhathe** [comment]
You can reproduce this with:

`expect([]).toEqual([])`

**Comment by jeremyhill-up** [comment]
+1, same deal here (comparing arrays for equality).

**Comment by slackersoft** [comment]
Closing this as a duplicate of #1188. The fix should be released in v2.5.1

**Comment by jonashartwig** [comment]
This seems to have returned in jasmine 2.6.0 went back to 2.5.2 to make it work.

**Comment by BenjenJones** [comment]
Same here. Please fix.

**Comment by enmanuelduran** [comment]
Happening to my team too!

**Comment by sanidz** [comment]
> This seems to have returned in jasmine 2.6.0 went back to 2.5.2 to make it work.

Version 2.6.2 has this problem after installing "@zxing/ngx-scanner": "^1.3.0"

**Comment by slackersoft** [comment]
2.6.2 is over a year old and we've released a new major version since then. Can you try updating to a more recent version of Jasmine? I'd like to confirm that the issue still exists since I'm not seeing any errors with the previous examples, like `expect([]).toEqual([])`.
