### ISSUE TITLE
Behaviour of stopSpecOnExpectationFailure=true + done.fail(Error)

### ISSUE THREAD

**Issue by wingedfox** [jasmine/jasmine#1245]
Hello,

Run: jasmine-npm
Version: 2.5.2
Node: 7.0.0

With the following

**Config:**
```json
{
  "stopSpecOnExpectationFailure": true,
}
```

**Test:**
```js
    it('Should fail in async before test', (done) => {
        Promise.reject(new Error('make me fail')).then((result) => {
            expect(result).toEqual(result);

            done();
        }).catch(done.fail);
    });
```

I have an error
```
(node:30498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error
(node:30498) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
F

Failures:
1) MalformedMessageError: Should fail in async before test
  Message:
    Failed: make me fail
  Stack:
    Error: make me fail
        at Object.it (/path/to.spec.js:34:24)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
```

There are 2 possible solutions:
1.  Make done.fail not to rethrow an error
2. Update docs to document such case

Both are OK for me, but it took several hours to find a root cause of test failures.

**Comment by slackersoft** [comment]
I'm not sure I fully understand what the problem is, but it sounds like it _might_ be:

1. Promise rejection handlers `catch` shouldn't throw errors.
2. Jasmine throws errors with failed expectations only with `stopSpecOnExpectationFailure` (there isn't any real other way to get an `expect` to break control flow of your spec)
3. `done.fail` adds a failed expectation so that the error message can be reported
4. When you combine 2 & 3, you cause `done.fail` to throw an error, and if that is in your promise rejection handler, that ends up wrapping the real expectation failure in the promise error message.
5. Additionally, because the `fail` portion now throws an error, Jasmine no longer proceeds to the next spec immediately, and you get the timeout error message as well.

We would be happy to review a pull request to address 5 for sure. Making the throw on failure logic know about `done.fail` in particular gets a little trickier, because a call to just `fail` should probably behave as a normal failed expectation.

**Comment by slackersoft** [comment]
I believe that issue number 5 should be fixed with the recent fix for #529 which should cause the `Error` to be caught and associated with the running spec.

Closing this. Thanks for using Jasmine!

**Comment by lselbeck** [comment]
I believe this is still an issue.  I'm reproing in jasmine 3.3.0 and npm 6.4.1 with the following code:
**Config:**
```
{
  "stopSpecOnExpectationFailure": true,
}
```

**Test:**
```
describe('test', () => {
    it('test', (done) => {
        return Promise.reject()
            .then(() => {
                done();
            })
            .catch(() => {
                done.fail('this should fail normally');
            });
    });
});
```

**Output:**
```
Jasmine started
(node:75318) UnhandledPromiseRejectionWarning: Error
    at Object.getJasmineRequireObj.errors (/{test_dir}/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2463:33)
    at Object.getJasmineRequire.core (/{test_dir}/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:49:26)
    at Object.module.exports [as boot] (/{test_dir}/node_modules/jasmine-core/lib/jasmine-core/node_boot.js:24:32)
    at new Jasmine (/{test_dir}/node_modules/jasmine/lib/jasmine.js:14:30)
    at Object.<anonymous> (/{test_dir}/config/testRunner.js:9:17)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
(node:75318) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:75318) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

test
  ✗ test
    - Failed: this should fail normally
    - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

**Comment by slackersoft** [comment]
Hmm, when I run that spec, I see:

```
○ → npx jasmine
Started
F

Failures:
1) test test
  Message:
    Failed: this should fail normally
  Stack:
    Error: Failed: this should fail normally
        at <Jasmine>
        at Promise.reject.then.catch (/Users/gregg/workspace/tester/spec/javascripts/spec.js:49:22)

1 spec, 1 failure
Finished in 0.005 seconds
```

Running Jasmine:
```
○ → npx jasmine -v
jasmine v3.3.1
jasmine-core v3.3.0
```
