### ISSUE TITLE
2.6 breaks support of using `toEqual(null)` and `toEqual(undefined)`

### ISSUE THREAD

**Issue by roni-frantchi** [jasmine/jasmine#1323]
Version: 2.6
Env: Browser.
Running using: Karma

In some cases we don't care wether the resultant value is `null` or `undefined`, so long as it's one of those.
For example, this helps especially when using a 3rd party library that may return one the former in one version, the the latter in another.
And so when attempting to assert that a value is either `null` or `undefined`, we have simply used something like:
```javascript
expect(result).toEqual(null);
```

In Jasmine 2.5, that worked as expected - 
```javascript
expect(null).toEqual(null); // pass
expect(undefined).toEqual(undefined); // pass
expect(undefined).toEqual(null); // pass
expect(0).toEqual(null); // fails
```

Jasmine 2.6 however, seems to introduce a breaking change:
```javascript
expect(result).toEqual(null); // RangeError: Invalid string length
```

**Comment by slackersoft** [comment]
Do you have any more information on stack trace for that `RangeError` you're seeing? I am not able to reproduce that.

Also, when I roll back and use jasmine 2.5.2 `expect(undefined).toEqual(null);` still fails, so I don't think this functionality should have changed in the 2.6 release.

**Comment by roni-frantchi** [comment]
@slackersoft I'm sorry, you're right.
Trying to isolate, it seems like the issue is completely different that what I had thought.

The test case that fails seems to involve using `toEqual()` on an Angular 2's `DebugElement`.

This used to work in 2.5.2:
```typescript
        let viewTestComponentFixture: ComponentFixture<ViewTestComponent>;

        beforeEach(async(() => {
            TestBed.compileComponents()
                .then(() => {
                    ViewTestComponentFixture = TestBed.createComponent(ViewTestComponent);
                    viewTestComponent = viewTestComponentFixture.componentInstance;
                });
        }));
...
domainInputDebugElement = viewTestComponentFixture.debugElement.query(d => d.name === "dcn-domain-input");
...
            it('should NOT have a domain input value element', async(() => {
                expect(domainInputDebugElement).not.toEqual(null);
            }));
```

While after upgrading Jasmine (and only Jasmine) to 2.6 it fails:
<details>
```	Failed: Invalid string length
	RangeError: Invalid string length
	    at Object.eval (modeling/src/app/decision/table/cell/edit/cell-operand.component.spec.ts:763:44 <- modeling/src/app/decision/table/cell/edit/cell-operand.component.spec.js:621:45)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:334:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:333:32)
	    at Zone.runGuarded (node_modules/zone.js/dist/zone.js:139:47)
	    at runInTestZone (node_modules/@angular/core/bundles/core-testing.umd.js:110:29)
	    at Object.eval (node_modules/@angular/core/bundles/core-testing.umd.js:49:17)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:334:26)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:79:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:333:32)
	    at Zone.run (node_modules/zone.js/dist/zone.js:126:43)
	    at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:102:34)
	    at eval (node_modules/@angular/core/bundles/core-testing.umd.js:96:21)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:334:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:333:32)
	    at Zone.run (node_modules/zone.js/dist/zone.js:126:43)
	    at AsyncTestZoneSpec.eval [as _finishCallback] (node_modules/@angular/core/bundles/core-testing.umd.js:91:29)
	    at node_modules/zone.js/dist/async-test.js:38:31
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:367:31)
	    at Zone.runTask (node_modules/zone.js/dist/zone.js:166:47)
	    at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:420:38)
	    at data.args.(anonymous function) (node_modules/zone.js/dist/zone.js:1581:29)
```
</details>

That said, it does not happen with any `ElementType`... I'll need to put some more time trying to isolate the root cause... I'll reopen a proper ticket once I do.

Thanks.

**Comment by emilio-martinez** [comment]
@roni-frantchi I found this kind of issue as well doing this type of test:
```ts
expect(componentInstance).toEqual(jasmine.any(ComponentClass));
```
That would give me `RangeError: Invalid string length`. However, in my case, neither expression evaluates to null. Removing the `jasmine.any` inside the `toEqual` seems to be what did it for me; I was able to "work around" this issue like so:
```ts
expect(componentInstance instanceof ComponentClass).toBeTruthy()
```
That said, it makes me think that somehow Jasmine is running out of memory? The expressions are individually calculated correctly; it's just equality + `.any` that messes it up.

FYI, I am also using Angular (4.1.3).

**Comment by slackersoft** [comment]
@emilio-martinez There were some issues like that invalid string length, but they should be fixed in the most recent 2.6.2 release.

**Comment by emilio-martinez** [comment]
@slackersoft Upgraded to `jasmine-core 2.6.2`. Still getting the same error. Not sure how helpful it might be, but below is the stack trace that I'm getting:
```
Uncaught RangeError: Invalid string length
    at Object.<anonymous> (http://localhost:9999/base/src/test.ts:34288:45)
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1154)
    at ProxyZoneSpec.onInvoke (http://localhost:9999/base/src/test.ts:28429:2160)
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1050)
    at Zone.run (http://localhost:9999/base/src/test.ts:28477:2925)
    at Object.<anonymous> (http://localhost:9999/base/src/test.ts:28363:131)
    at http://localhost:9999/base/src/test.ts:6511:46
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1154)
    at AsyncTestZoneSpec.onInvoke (http://localhost:9999/base/src/test.ts:28268:156)
    at ProxyZoneSpec.onInvoke (http://localhost:9999/base/src/test.ts:28429:2040)
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1050)
    at Zone.run (http://localhost:9999/base/src/test.ts:28477:2925)
    at AsyncTestZoneSpec._finishCallback (http://localhost:9999/base/src/test.ts:6510:13)
    at http://localhost:9999/base/src/test.ts:28265:139
    at ZoneDelegate.invokeTask (http://localhost:9999/base/src/test.ts:28493:2120)
    at Zone.runTask (http://localhost:9999/base/src/test.ts:28482:417)
    at ZoneTask.invoke (http://localhost:9999/base/src/test.ts:28495:975)
    at timer (http://localhost:9999/base/src/test.ts:28627:248)
```
Also worth noting is that I get a `[Violation] 'setTimeout' handler took 14605ms` warning in "Verbose" log mode in the Chrome Dev Tools. I believe that's because whatever's causing the error takes a bit before ending up in the `RangeError`.

The `at Object.<anonymous> [...]/test.ts:34288:45` reference at the very top refers to exactly the point where `.toEqual` is called. In my tests, I have only two instances of `.toEqual(jasmine.any(ComponentClass)`, both of which fail in the same manner. Changing to the `instanceof` approach not only removes the error but also doesn't cause the `Violation` warning.

**Comment by slackersoft** [comment]
@emilio-martinez can you please open a new issue for this error, as it doesn't seem to be related to using `toEqual` with `null` or `undefined`.

**Comment by emilio-martinez** [comment]
@slackersoft done!
