### ISSUE TITLE
expect...toEqual doesn't check for symbol keys

### ISSUE THREAD

**Issue by crfrolik** [jasmine/jasmine#1811]
## Expected Behavior

```
const sym = Symbol('foo');
expect({}).toEqual({[sym]: 'foo'});
```

This test should fail. It currently passes.

## Current Behavior

`toEqual` should compare symbol keys as well as string keys.

## Your Environment

* Version used:  `jasmine-core`: `3.5.0`,
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 80, node 13.9.0
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by sgravrock** [comment]
Agreed. I'd be happy to review a pull request that fixes this.

**Comment by sgravrock** [comment]
This was fixed in the PRs mentioned in the above merge, and will be in the next minor release.

**Comment by Toxicable** [comment]
Hey @sgravrock was this actually merged in? I cant see it on main and still have this issue using version 3.7.x

**Comment by sgravrock** [comment]
Hmm, I must have commented on the wrong issue by mistake. This wasn't mergeable in 3.x because it broke Internet Explorer. I've merged it now and it should be in 4.1.
