### ISSUE TITLE
Clock uninstall doesn't work if spy is added on setTimeout after installation

### ISSUE THREAD

**Issue by chrisirhc** [jasmine/jasmine#826]
See the following block:

``` js
describe('clock calls', function () {
    beforeEach(function () {
        jasmine.clock().install();
    });

    afterEach(function () {
        jasmine.clock().uninstall();
    });

    it('', function () {
        spyOn(window, 'setTimeout');
    });
});

it('', function () {
    // window.setTimeout is still non-native
})
```

If a spy is added on window.setTimeout after `clock().install();`, the `clock().uninstall()` doesn't uninstall on window.setTimeout.

I also noted that adding the spy before clock installation works with expected behavior, though.

**Comment by slackersoft** [comment]
What version of jasmine are you using? When I try a slightly modified version it seems to be working correctly to me

````javascript
describe('clock calls', function () {
  beforeEach(function () {
    jasmine.clock().install();
  });

  afterEach(function () {
    jasmine.clock().uninstall();
  });

  it('spies on setTimeout', function () {
    spyOn(window, 'setTimeout');
    expect(window.setTimeout.calls).not.toBeUndefined();
  });
});

it('has a native setTimeout', function () {
  expect(window.setTimeout.calls).toBeUndefined();
});
````

**Comment by chrisirhc** [comment]
I'm using 2.2.0 . Perhaps this has been resolved in 2.2.1 .

**Comment by czajkowski** [comment]
I ma having a similar problem in 2.3.0. 

Clock is not being uninstalled correctly when we use spyOn(window, "clearTimeout") in our tests.

The problem doesn't exist when we move installing/uninstalling the clock to beforeAll/afterAll.

**Comment by slackersoft** [comment]
I think I know what's going on here, and why the spec I wrote was passing while you are still seeing the issue. What's happening in this situation is:

1. `clock().install()` replaces all of the timing functions on window with stubs
1. `spyOn` then replaces the replacement with a stub and remembers the previous function (which is the stubbed version from the clock)
1. `clock().uninstall()` reinstalls the built-in timing functions
1. spies get cleaned up after all `afterEach` functions are called and this replaces the real timing functions with the "original" function at the time the function was spied on.

This means that the default clock uninstall is getting overridden when the spy is uninstalled. For this reason at least, you probably shouldn't be spying on timing functions when using jasmine's mock clock

I hope this helps. Thanks for using jasmine!

**Comment by chrisirhc** [comment]
This makes it very difficult to test whether tests are actually calling the timing functions, and with which arguments.

For example, allowing the following in a test:
```
expect(setTimeout).toHaveBeenCalledWith(jasmine.any(Function), 5000);
jasmine.clock().tick(5000);
```

I'm thinking there's two ways to achieve this:
- Allow access to the jasmine clock instance and allow mocking it.
- All replaced methods are also spies, or have an option for this.

**Comment by slackersoft** [comment]
For any given spec, you should either use spies to assert that you call the timing functions exactly how you want, or use the mock clock and do something like:

````javascript
jasmine.clock().install();
// call the thing that calls setTimeout

jasmine.clock().tick(5000);
// expect the effects from the background call

// and if you want to also check that you used setTimeout and not setInterval
jasmine.clock.tick(5000);
// expect not to have duplicates.
````

**Comment by chrisirhc** [comment]
I'm aware that those are my current options. However, what I'm asking is to allow for spying on the timing functions after installing the mock clock. The reason for this is that I'm testing code that's supposed to run asynchronously. setTimeout and setInterval are called multiple times. I need to check that they're called with the correct arguments *and* ensure that they run at in the time order that they were invoked with.

The first thing that came to mind was to mock the clock. Now with the current solution, I'm faced with the choice of mocking the clock myself instead of using Jasmine's mock clock as I cannot both spy the methods and use the mock clock.

**Comment by slackersoft** [comment]
If you really think you need to assert that the delay that was passed to `setTimeout` was 5000 and not 4999, then you should probably use spies. I can't think of an application where I would need that level of specificity. Additionally, when you spy on the functions, the best you can check for with the actual function that is passed is `jasmine.any(Function)` which isn't helpful. If you want to test the side effects, you're left executing the function yourself.

On the other hand, if you use the mock clock, you can `tick()` to just after each of your `setTimeout`s and `setInterval`s should be scheduled, and you should see everything run. You can do as many or as few `tick()`s during a spec as you want, so there should be no problem to test multiple `setTimeout` and `setInterval` calls. And if you want, you can always `tick()` to some value under the expected 5000, and assert that nothing has changed before `tick()`ing the remainder of the way to 5000.

**Comment by chrisirhc** [comment]
Take for example, an application where the setTimeout time was not constant, but a variable. You need to both assert that it was called with the correct time, and make sure that they're executed in order.

I think your solution works fine if the assumption is that I'm testing an expected constant timeout. However, that's not a case. I'm working with an asynchronous API where certain events need to happen with variable timeout. Not only that, setTimeout is called several times with different functions. I would like to test that the specific functions are called with the correct timeouts.

Since the timeout is variable, and the function is *not*, I'm able to check whether setTimeout is called with a specific function (since it doesn't necessarily have to be called with an anonymous function) rather than *any* function.

I know that Jasmine has the methods for doing such specific testing and matching, which is why I picked this excellent framework. It's just the usage of the mock clock negates this capability for timing functions.

**Comment by slackersoft** [comment]
If your test is checking the exact timeout that is passed to `setTimeout`, then you by definition have enough information to instead step forward that number of milliseconds in the mock clock. So even if you have an algorithm for figuring out how long to delay an action, and not just a constant number, you should still be able to use the mock clock.

If you feel you need to have some specs that `spyOn` some of the timing functions, these should probably be separate from the specs that use the mock clock to run the asynchronous functions.

I don't think this is functionality that we are likely to change. The two solutions I can think of are:

1. No longer automatically clean up spies for you at the end of your spec.
2. Start automatically uninstalling the clock again, so we can control order of cleanup.

We don't want to do 1. because that would leave a large burden on the user writing the specs to remember to clean up their spies when done (and do it in the proper order).

I'm not sure we want to do 2. either. When we were working on 2.0, we made the decision to require an explicit uninstall of the mock clock to make it work more like other plugins that needed explicit install/uninstall steps.

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue in a while, so I'm going to close it for now. Feel free to continue discussion here.

**Comment by nwhite89** [comment]
I'm having a very similar issue I need to have the `clearInterval` inside the `setInvterval` as I need to ensure that the `interval` is removed after running `x` amount of times. This works in `2.1.3` however, moving ahead then fails any ideas?

**Comment by slackersoft** [comment]
@nwhite89 I don't think that is related to this issue. Can you open a new issue with an example suite that fails and what the failure mode is so we can look into it?

Thanks for using Jasmine!

**Comment by KayKadner** [comment]
@slackersoft : I would like to reopen the discussion here, as I think that spyOn timing functions and jasmine.clock() do not work together and should be prevented on jasmine level. Maybe similar to trying to spy on a spy, by throwing an error. 

The problem of your example in https://github.com/jasmine/jasmine/issues/826#issuecomment-94558153 is that you check for window.setTimeout.calls, which is of course not defined, because you look there at the clocked version of setTimeout and this has no "calls" property. If you change the test to 
```js
const originalSetTimeout = window.setTimeout;
describe("clock calls", function () {
  beforeEach(function () {
    jasmine.clock().install();
  });

  afterEach(function () {
    jasmine.clock().uninstall();
  });

  it("spies on setTimeout", function () {
    spyOn(window, "setTimeout");
    expect(window.setTimeout.calls).not.toBeUndefined();
  });
});

it("has a native setTimeout", function () {
  expect(window.setTimeout).toBe(originalSetTimeout);
  // fails
});

it("successfuly uses setTimeout", function (done) {
  setTimeout(done, 0); // fails as well, as it tries to use the clock'ed version of setTimeout
});
```
you see that it does not work. And you describe the issue in https://github.com/jasmine/jasmine/issues/826#issuecomment-100028373 absolutely correct. 

To summarize, it does not make sense to spyOn(window, "setTimeout") and the other timing functions, if a clock is installed. If you
- install/uninstall the clock in beforeEach/afterEach, you'll end up with broken timing functions, as the clock is uninstalled first (putting back the native functions) and afterwards spies are reset (replacing the native functions with clocked versions). ==> timing functions are broken
- install/uninstall the clock in beforeAll/afterAll, the spies are set and reset correctly, but without callThrough() spy strategy, the timing functions don't do their clocked magic. If they stub(), nothing happens, but if they callFake(), they do something unexpected wrt. clock() behaviour. 
- if you spyOn first and then install the clock, you cannot use the spy anymore, e.g., check for call counts etc.

I see two solutions:
1. throw an error if people try to spy on a clock function
2. make the clock'ed timing functions behave like spies, i.e., allow toHaveBeenCallled matchers and so on.

This issue caused some flaky tests for us because some async backend request, which does not matter for the test, returned sometimes late enough to call a setTimeout afterwards leading to a crash.

**Comment by sgravrock** [comment]
>    1. throw an error if people try to spy on a clock function

That seems reasonable to me. I'd be happy to review a PR that does that.

One could argue that it's a breaking change (and thus would have to be parked on a branch for the foreseeable future), but I think it's reasonable for new diagnostics for already-broken code to be semver-minor. And inadvertently leaking the mock clock certainly counts as broken.

>    2. make the clock'ed timing functions behave like spies, i.e., allow toHaveBeenCallled matchers and so on.

I'm pretty skeptical about this. I suspect that most specs that mix the mock clock and spying on `setTimeout` would be improved by switching to use only one or the other kind of mock. Granted, most is not the same as all. But I think I'd need to see much stronger signs of user interest than the decade of silence on this issue, as well as examples of real-world specs that would be made worse by not being able to mock `setTimeout` two ways at once.
